[package]
name = "wcc"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
globset = "0.4.16"
[dev-dependencies]
tempfile = "3"